name: docker

on:
  push:
    branches: [main]
  release:
    types: [published]

permissions:
  contents: read

env:
  REPO: cobaltt7/test

jobs:
  build:
    name: build (${{ matrix.platform }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux/amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Login to DockerHub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Name image
        id: image
        run: echo "image=image-${ARCH/\//-}" >> "$GITHUB_OUTPUT"
        env:
          ARCH: ${{ matrix.platform }}

      - name: Build and export
        id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          platforms: ${{ matrix.platform }}
          tags: ${{ env.REPO }}
          # prettier-ignore
          outputs:
            type=image,push=true,push-by-digest=true,name-canonical=true,dest=images/${{ steps.image.outputs.image }}.tar
          cache-from: type=gha,scope=${{ steps.image.outputs.image }}
          cache-to: type=gha,scope=${{ steps.image.outputs.image }},mode=max

      - name: Image digest
        run: echo "$DIGEST"
        env:
          DIGEST: ${{ steps.build.outputs.digest }}

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.digest }}
          path: images/${{ steps.image.outputs.image }}.tar

  push:
    # if: github.repository == 'psf/black'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Login to DockerHub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Download images
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          merge-multiple: true
          path: images
          pattern: image-*

      - name: Create manifest list and push
        run: |
          TAGS="-t $REPO:latest"

          if [[ "$EVENT_NAME" == "release" ]]; then
            TAGS="$TAGS -t $REPO:$(git describe --candidates=0 --tags)"

            if [[ "$PRERELEASE" == "true" ]]; then
              TAGS="$TAGS -t $REPO:latest_prerelease"
            else
              TAGS="$TAGS -t $REPO:latest_release"
            fi
          else
            TAGS="$TAGS -t $REPO:latest_non_release"
          fi

          cd images
          docker buildx imagetools create $TAGS $(printf '$REPO@sha256:%s ' *)
        env:
          EVENT_NAME: ${{ github.event_name }}
          PRERELEASE: ${{ github.event.release.prerelease }}

      - name: Inspect image
        run: docker buildx imagetools inspect $REPO:latest
