name: fuzz

on:
  push:
    branches: main
  pull_request:
    paths:
      - .github/workflows/fuzz.yml
      - scripts/fuzz.py
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  fuzz:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
          pip-version: "25.3"
          pip-install: --group tox

      - name: Run fuzz tests
        run: tox -e fuzz --result-json "$python_ver.json"
        env:
          python_ver: ${{ matrix.python-version }}

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: always()
        with:
          name: ${{ matrix.python-version }}.json
          path: ${{ matrix.python-version }}.json

  create-issue:
    runs-on: ubuntu-latest
    needs: fuzz
    if:
      always() && github.repository == 'cobaltt7/black' && github.event_name !=
      'pull_request' && needs.fuzz.result != 'success'
    permissions:
      issues: write
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          merge-multiple: true
          path: ./output

      - name: Generate issue data
        run: |
          output="issue-body.html"
          touch $output
          for FILE in *; do
            echo "<details>" >> $output
              echo "<summary><b>Python $FILE</b></summary>" >> $output
              echo "<pre>$(jq .testenvs.fuzz.test[-1].output $FILE)</pre>" >> $output
              echo "<pre>$(jq .testenvs.fuzz.test[-1].err $FILE)</pre>" >> $output
            echo "</details>" >> $output
          done

      - name: Get existing issue
        id: issue
        run: |
          echo "ISSUE=$( \
            gh issue list \
              -A github-actions[bot] -l 'ci: fuzz error' \
              --json number -q .[0].number \
          )" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create new issue
        if: steps.issue.outputs.ISSUE == ''
        run: >
          gh issue create -t "Fuzz test failure" -l "ci: fuzz error" -f issue-body.html
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Edit existing issue
        if: steps.issue.outputs.ISSUE != ''
        run: gh issue edit $ISSUE -f issue-body.html
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ISSUE: ${{ steps.issue.outputs.ISSUE }}
